package enums;

public enum Face {
	ACE_SPADES, ACE_CLUBS, ACE_DIAMONDS, ACE_HEARTS,
	TWO_SPADES, TWO_CLUBS, TWO_DIAMONDS, TWO_HEARTS,
	THREE_SPADES, THREE_CLUBS, THREE_DIAMONDS, THREE_HEARTS,
	FOUR_SPADES, FOUR_CLUBS, FOUR_DIAMONDS, FOUR_HEARTS,
	FIVE_SPADES, FIVE_CLUBS, FIVE_DIAMONDS, FIVE_HEARTS,
	SIX_SPADES, SIX_CLUBS, SIX_DIAMONDS, SIX_HEARTS,
	SEVEN_SPADES, SEVEN_CLUBS, SEVEN_DIAMONDS, SEVEN_HEARTS,
	EIGHT_SPADES, EIGHT_CLUBS, EIGHT_DIAMONDS, EIGHT_HEARTS,
	NINE_SPADES, NINE_CLUBS, NINE_DIAMONDS, NINE_HEARTS,
	TEN_SPADES, TEN_CLUBS, TEN_DIAMONDS, TEN_HEARTS,
	JACK_SPADES, JACK_CLUBS, JACK_DIAMONDS, JACK_HEARTS,
	QUEEN_SPADES, QUEEN_CLUBS, QUEEN_DIAMONDS, QUEEN_HEARTS,
	KING_SPADES, KING_CLUBS, KING_DIAMONDS, KING_HEARTS
}